from engine.eligibility import evaluate_eligibility

from agents.state import LoanAdvisoryState


def underwriting_agent(state: LoanAdvisoryState):
    """
    Apply deterministic product eligibility rules and produce
    the underwriting decision for the current loan request.

    The decision is generated by the rule-based eligibility engine,
    not by the Generative AI model.
    """

    customer = state["customer"]
    product = state["product"]

    eligibility_result = evaluate_eligibility(
        customer=customer,
        product=product,
        requested_amount=state["requested_amount"],
        requested_tenure=state["requested_tenure"],
        foir=state["foir"]
    )

    audit_entry = {
        "agent": "Underwriting Decision Agent",
        "action": "Evaluated deterministic loan eligibility rules.",
        "details": {
            "decision": eligibility_result["decision"],
            "reasons": eligibility_result["reasons"]
        }
    }

    audit_trail = state.get(
        "audit_trail",
        []
    ) + [audit_entry]

    return {
        "decision": eligibility_result["decision"],
        "reasons": eligibility_result["reasons"],
        "audit_trail": audit_trail
    }